# Basic
name:               "Sullam Jeoung"

author:
  facebook:         #your-id
  youtubeUser:      #your-id
  youtubeChannel:   #your-id
  twitter:          #your-id
  github:           sullamij
  stackoverflow:    #your-id
  quora:            #your-id
  linkedin:         #your-id
  pinterest:        #your-id
  googlePlus:       #your-id
  instagram:        #your-id
  reddit:           #your-id
  medium:           #your-id
  tumblr:           #your-id
  email:            sullamij@gmail.com

copyright:
  year:             2018
  name:             Sullam Jeoung

# Google-analytics
google-analytics:
  id:               "UA-150444557-1"

# Disqus
disqus:
  id:               "sullam"

# URL
url:                "https://sullamij.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            #"" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

#favicon
favicon: favicon.ico

# Markdown
markdown:           kramdown

#Added for math equation
highlighter:        rouge
lsi:                false
excerpt_seperator:  "\n\n"
incremental:        false
###
kramdown:
  input:            GFM

# Navigation
nav:
#  - name:           "About"
#    url:            "/about"
#  - name:           "Archive"
#    url:            "/archive"
  - name:           "CV"
    url:            "/cv"
  - name:           "Categories"
    url:            "/categories"
  - name:           "Tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

  
# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# optional features
show_related_posts: true

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jemoji
 


exclude:            [vendor]
